# Generated by Django 5.1.4 on 2025-01-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qq',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
